# Generated by Django 4.2 on 2023-05-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_departamento_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.IntegerField(primary_key='True', serialize=False, verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='Nombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('0', 'Contador'), ('1', 'Administrador'), ('2', 'Economista'), ('3', 'Otro')], max_length=50, verbose_name='Trabajo')),
            ],
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.AddField(
            model_name='articulo',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nombre'),
        ),
    ]
