# Generated by Django 4.2 on 2023-05-29 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_articulo_nombre_remove_empleado_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nombre',
            name='job',
            field=models.CharField(choices=[('0', 'Silla'), ('1', 'Banco'), ('2', 'Pizarron')], max_length=50, verbose_name='Catalogo'),
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.IntegerField(primary_key='True', serialize=False, verbose_name='id')),
                ('fecha', models.IntegerField(verbose_name='fecha')),
                ('cantidad', models.IntegerField()),
                ('observacion', models.CharField(max_length=50, verbose_name='observacion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.articulo')),
            ],
        ),
    ]
