# Generated by Django 4.2 on 2023-05-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_nombre_job_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Catalogo'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='fecha',
            field=models.CharField(max_length=50, verbose_name='fecha'),
        ),
        migrations.DeleteModel(
            name='Nombre',
        ),
    ]
