# Generated by Django 4.2 on 2023-05-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_articulo_id_alter_articulo_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='fecha'),
        ),
    ]
